export type {
  PerkRef,
  PerkColumn,
  InternedPerkColumn,
  WeaponStat,
  ArmorStat,
  WeaponDoc,
  WeaponSummary,
  WeaponDetailFields,
  WeaponIndex,
  WeaponDetailIndex,
  DamageTypeRef,
  ArmorDoc,
  ArmorIndex,
  ArmorArchetypeRef,
  Armor30SetRef,
} from "./types";
export {
  PLUG_CATEGORY_ARMOR_ARCHETYPES,
  PLUG_CATEGORY_TUNING_MODS,
  PLUG_CATEGORY_ARMOR3_MASTERWORKS,
  ARMOR3_STAT_HASHES,
  ARMOR3_STAT_NAME_BY_HASH,
  ARMOR3_STAT_ICON_BY_HASH,
  TUNING_MOD_TO_STAT_HASH,
} from "./armor30-constants";
export {
  isArmor30ItemDef,
  resolveArchetypeFromSockets,
  resolveArmor30Stats,
  resolveTertiaryStat,
  resolveTunableStat,
  findTuningSocketIndex,
  resolveArchetypeFromPlugMap,
  resolveTunableStatFromReusablePlugs,
  resolveTunableStatForInstance,
  buildArchetypeMap,
  type Armor30StatRoll,
  type ItemSocketPlug,
  type ItemStat,
  type ReusablePlug,
} from "./armor-instance";
export {
  expandWeapon,
  buildPerkMapFromCatalog,
  internWeaponCatalog,
  normalizeWeaponIndex,
  buildDetailIndexFromDocs,
  summariesForPerkName,
  resolveInternedColumns,
  isLegacyWeaponDoc,
} from "./intern-weapons";
export {
  filterWeapons,
  sortWeapons,
  weaponsWithPerk,
  createWeaponFuse,
  fuzzySearchWeapons,
  collectFacets,
  collectPerks,
  collectColumnPerks,
  suggestWeaponNames,
  buildPerkMap,
  buildWeaponsByPerkName,
  type WeaponSort,
  type WeaponFilters,
  type FacetOption,
  type PerkOption,
  type ColumnPerkOptions,
} from "./search";
export {
  buildWeaponIndexLookups,
  type WeaponIndexLookups,
} from "./weapon-index-lookups";
export {
  filterArmor,
  sortArmor,
  createArmorFuse,
  fuzzySearchArmor,
  collectArmorFacets,
  collectArmorMods,
  buildModMap,
  buildArchetypeMapFromIndex,
  type ArmorSort,
  type ArmorFilters,
  type ModOption,
} from "./armor-search";
export { sampleWeapons } from "./fixtures/sample-weapons";
export { sampleDamageTypes } from "./fixtures/sample-damage-types";
export { sampleArmor } from "./fixtures/sample-armor";
export {
  buildWeaponDpsIndex,
  extractTraitPerksFromRow,
  formatWeaponDpsLabel,
  matchSheetRowToWeapon,
  parseDpsNumber,
  parseTotalDamage,
  weaponDpsLookupFromIndex,
  WEAPON_DPS_SHEET_CSV_URL,
  WEAPON_DPS_SHEET_NAME,
  type WeaponDpsCatalogEntry,
  type WeaponDpsEntry,
  type WeaponDpsIndex,
  type WeaponDpsLookup,
} from "./weapon-dps";
