export type {
  PerkRef,
  PerkColumn,
  InternedPerkColumn,
  WeaponStat,
  ArmorStat,
  WeaponDoc,
  WeaponSummary,
  WeaponDetailFields,
  WeaponIndex,
  WeaponDetailIndex,
  WeaponCatalogBaseline,
  WeaponCatalogDiffSource,
  NewWeaponIndex,
  DamageTypeRef,
  WeaponTypeRef,
  AmmoTypeRef,
  ArmorDoc,
  ArmorIndex,
  ArmorArchetypeRef,
  Armor30SetBonus,
  Armor30SetRef,
  StatMod,
  StatGroupRef,
  StatGroupScaledStat,
  StatInterpolationPoint,
  MasterworkOption,
} from "./types";
export {
  PLUG_CATEGORY_ARMOR_ARCHETYPES,
  PLUG_CATEGORY_TUNING_MODS,
  PLUG_CATEGORY_ARMOR3_MASTERWORKS,
  ARMOR3_STAT_HASHES,
  ARMOR3_STAT_NAME_BY_HASH,
  ARMOR3_STAT_ICON_BY_HASH,
  ARMOR_STAT_PLUG_CATEGORIES,
  TUNING_MOD_TO_STAT_HASH,
} from "./armor30-constants";
export {
  isArmor30ItemDef,
  resolveArchetypeFromSockets,
  resolveArmor30Stats,
  resolveTertiaryStat,
  resolveTunableStat,
  findTuningSocketIndex,
  resolveArchetypeFromPlugMap,
  resolveTunableStatFromReusablePlugs,
  resolveTunableStatForInstance,
  buildArchetypeMap,
  collectArmorStatAdjustingPlugHashes,
  subtractEquippedPlugStatBonuses,
  type Armor30StatRoll,
  type ItemSocketPlug,
  type ItemStat,
  type ReusablePlug,
} from "./armor-instance";
export {
  expandWeapon,
  buildPerkMapFromCatalog,
  internWeaponCatalog,
  enrichAmmoGenerationFromDetails,
  normalizeWeaponIndex,
  buildDetailIndexFromDocs,
  summariesForPerkName,
  resolveInternedColumns,
  isLegacyWeaponDoc,
} from "./intern-weapons";
export {
  matchRank,
  effectiveRank,
  rankLabeledOptions,
  ghostSuffix,
  bestGhostSuffix,
  bestGhostCompletion,
  createPerkNameFuse,
  filterPerkNames,
  rankPerkNames,
  suggestPerkNames,
  type RankedLabel,
  type GhostCompletion,
  type PerkNameEntry,
  type FilteredPerkName,
} from "./suggest";
export {
  filterWeapons,
  sortWeapons,
  weaponsWithPerk,
  createWeaponSearcher,
  type WeaponSearcher,
  fuzzySearchWeapons,
  collectFacets,
  collectActivitySourceFacets,
  type CollectActivitySourceFacetsOptions,
  collectRaidSourceFacets,
  type CollectRaidSourceFacetsOptions,
  collectPerks,
  collectColumnPerks,
  filterWeaponNames,
  sortFilteredWeaponNames,
  hasStrongWeaponNameMatch,
  MIN_WEAPON_TEXT_QUERY_LENGTH,
  weaponsMatchingTextQuery,
  rankWeaponResults,
  suggestWeaponNames,
  buildPerkMap,
  buildWeaponsByPerkName,
  buildWeaponNameIndex,
  type WeaponSort,
  type WeaponFilters,
  type FacetOption,
  type PerkOption,
  type ColumnPerkOptions,
  type WeaponNameIndex,
  type PopularityLookup,
} from "./search";
export { isDamagePerk, damagePerkIndexSet, collectDamagePerkNames } from "./damage-perks";
export {
  parseWeaponQuery,
  planWeaponTextSearch,
  mergeWeaponFilters,
  ARRAY_FACET_KEYS,
  type ParsedWeaponQuery,
  type WeaponTextSearchPlan,
} from "./query-language";
export { expandWeaponQueryAliases, WEAPON_NAME_ALIASES } from "./aliases";
export { createLruCache, type LruCache } from "./lru-cache";
export {
  buildWeaponIndexLookups,
  refreshWeaponSummaries,
  type WeaponIndexLookups,
} from "./weapon-index-lookups";
export {
  DEFAULT_GENERATED_DATA_PATHS,
  GENERATED_DATA_MANIFEST_FILENAME,
  GENERATED_DATA_MANIFEST_PATH,
  generatedDataCacheMode,
  generatedDataPath,
  type GeneratedDataKey,
  type GeneratedDataManifest,
  type GeneratedDataManifestFile,
} from "./generated-data-manifest";
export { buildNewWeaponIndex } from "./new-weapons";
export {
  filterArmor,
  sortArmor,
  createArmorFuse,
  fuzzySearchArmor,
  collectArmorFacets,
  collectArmorMods,
  buildModMap,
  buildArchetypeMapFromIndex,
  type ArmorSort,
  type ArmorFilters,
  type ModOption,
} from "./armor-search";
export {
  collectOwnedArmorFacets,
  createOwnedArmorFuse,
  filterOwnedArmor,
  searchOwnedArmor,
  sortOwnedArmor,
  type OwnedArmorFilters,
  type OwnedArmorSearchItem,
} from "./owned-armor-search";
export {
  ACTIVITY_INTRO_SEASON,
  ACTIVITY_SOURCE_ALIASES,
  CURATED_SOURCE_LABELS,
  DUNGEON_SOURCE_ALIASES,
  DUNGEON_SOURCE_LABELS,
  EVENT_SOURCE_ALIASES,
  EVENT_SOURCE_LABELS,
  OPS_SOURCE_ALIASES,
  OPS_SOURCE_LABELS,
  RAID_SOURCE_ALIASES,
  RAID_SOURCE_LABELS,
  activitySourceMatchesQuery,
  canonicalActivitySource,
  canonicalRaidSource,
  isCuratedActivitySource,
  isDungeonSource,
  isRaidSource,
  matchesWeaponSource,
  normalizeWeaponSource,
  raidSourceMatchesQuery,
  resolveWeaponSources,
  sourceFields,
  sourceLabels,
  resolveWeaponSeason,
  type ResolvedWeaponSources,
  type ResolvedWeaponSeason,
} from "./weapon-provenance";
export { abbreviateWeaponType } from "./weapon-type-abbrev";
export {
  collapseWeaponVersions,
  currentWeaponPerkPoolVersions,
  isCatalogWeapon,
  originTraitNamesForWeapon,
  originTraitNamesForWeapons,
  primaryCatalogWeaponForHash,
  primaryWeaponVersion,
  reconcileAdeptTierPools,
  reconcileCraftableTwins,
  sortWeaponVersions,
  weaponPerkPoolVersionForHash,
  weaponVersionFamilyName,
  weaponsInVersionFamily,
  weaponVersionSortKey,
  type CurrentWeaponPerkPoolVersion,
} from "./weapon-variants";
export { sampleWeapons } from "./fixtures/sample-weapons";
export { sampleDamageTypes } from "./fixtures/sample-damage-types";
export { sampleWeaponTypes } from "./fixtures/sample-weapon-types";
export { sampleAmmoTypes } from "./fixtures/sample-ammo-types";
export { sampleArmor } from "./fixtures/sample-armor";
export {
  computeWeaponStats,
  interpolateStatValue,
  sampleStatGroup,
  AMMO_GENERATION_STAT_HASH,
  scaleInvestmentStats,
  sumInvestmentStats,
  SAMPLE_STAT_GROUP_HASH,
  type ComputedWeaponStats,
} from "./weapon-stats";
export {
  buildWeaponMasterworkOptions,
  WEAPON_MASTERWORK_SOCKET_TYPE_HASH,
} from "./weapon-masterwork";
export {
  buildWeaponDpsIndex,
  extractTraitPerksFromRow,
  formatBuildDescription,
  formatWeaponDpsLabel,
  formatWeaponDpsParts,
  matchSheetRowToWeapon,
  parseDpsNumber,
  parseTotalDamage,
  weaponDpsLookupFromIndex,
  WEAPON_DPS_SHEET_CSV_URL,
  WEAPON_DPS_SHEET_NAME,
  WEAPON_DPS_SHEET_URL,
  type WeaponDpsCatalogEntry,
  type WeaponDpsEntry,
  type WeaponDpsIndex,
  type WeaponDpsLookup,
} from "./weapon-dps";
