export type {
  PerkRef,
  PerkColumn,
  InternedPerkColumn,
  WeaponStat,
  ArmorStat,
  WeaponDoc,
  WeaponSummary,
  WeaponDetailFields,
  WeaponIndex,
  WeaponDetailIndex,
  DamageTypeRef,
  WeaponTypeRef,
  AmmoTypeRef,
  ArmorDoc,
  ArmorIndex,
  ArmorArchetypeRef,
  Armor30SetRef,
  StatMod,
  StatGroupRef,
  StatGroupScaledStat,
  StatInterpolationPoint,
} from "./types";
export {
  PLUG_CATEGORY_ARMOR_ARCHETYPES,
  PLUG_CATEGORY_TUNING_MODS,
  PLUG_CATEGORY_ARMOR3_MASTERWORKS,
  ARMOR3_STAT_HASHES,
  ARMOR3_STAT_NAME_BY_HASH,
  ARMOR3_STAT_ICON_BY_HASH,
  TUNING_MOD_TO_STAT_HASH,
} from "./armor30-constants";
export {
  isArmor30ItemDef,
  resolveArchetypeFromSockets,
  resolveArmor30Stats,
  resolveTertiaryStat,
  resolveTunableStat,
  findTuningSocketIndex,
  resolveArchetypeFromPlugMap,
  resolveTunableStatFromReusablePlugs,
  resolveTunableStatForInstance,
  buildArchetypeMap,
  type Armor30StatRoll,
  type ItemSocketPlug,
  type ItemStat,
  type ReusablePlug,
} from "./armor-instance";
export {
  expandWeapon,
  buildPerkMapFromCatalog,
  internWeaponCatalog,
  enrichAmmoGenerationFromDetails,
  normalizeWeaponIndex,
  buildDetailIndexFromDocs,
  summariesForPerkName,
  resolveInternedColumns,
  isLegacyWeaponDoc,
} from "./intern-weapons";
export {
  matchRank,
  effectiveRank,
  rankLabeledOptions,
  ghostSuffix,
  bestGhostSuffix,
  bestGhostCompletion,
  createPerkNameFuse,
  filterPerkNames,
  rankPerkNames,
  suggestPerkNames,
  type RankedLabel,
  type GhostCompletion,
  type PerkNameEntry,
  type FilteredPerkName,
} from "./suggest";
export {
  filterWeapons,
  sortWeapons,
  weaponsWithPerk,
  createWeaponFuse,
  fuzzySearchWeapons,
  collectFacets,
  collectPerks,
  collectColumnPerks,
  filterWeaponNames,
  sortFilteredWeaponNames,
  MIN_WEAPON_TEXT_QUERY_LENGTH,
  weaponsMatchingTextQuery,
  rankWeaponResults,
  suggestWeaponNames,
  buildPerkMap,
  buildWeaponsByPerkName,
  type WeaponSort,
  type WeaponFilters,
  type FacetOption,
  type PerkOption,
  type ColumnPerkOptions,
} from "./search";
export {
  buildWeaponIndexLookups,
  refreshWeaponSummaries,
  type WeaponIndexLookups,
} from "./weapon-index-lookups";
export {
  filterArmor,
  sortArmor,
  createArmorFuse,
  fuzzySearchArmor,
  collectArmorFacets,
  collectArmorMods,
  buildModMap,
  buildArchetypeMapFromIndex,
  type ArmorSort,
  type ArmorFilters,
  type ModOption,
} from "./armor-search";
export {
  collectOwnedArmorFacets,
  createOwnedArmorFuse,
  filterOwnedArmor,
  searchOwnedArmor,
  sortOwnedArmor,
  type OwnedArmorFilters,
  type OwnedArmorSearchItem,
} from "./owned-armor-search";
export { sampleWeapons } from "./fixtures/sample-weapons";
export { sampleDamageTypes } from "./fixtures/sample-damage-types";
export { sampleWeaponTypes } from "./fixtures/sample-weapon-types";
export { sampleAmmoTypes } from "./fixtures/sample-ammo-types";
export { sampleArmor } from "./fixtures/sample-armor";
export {
  computeWeaponStats,
  interpolateStatValue,
  sampleStatGroup,
  AMMO_GENERATION_STAT_HASH,
  scaleInvestmentStats,
  sumInvestmentStats,
  SAMPLE_STAT_GROUP_HASH,
  type ComputedWeaponStats,
} from "./weapon-stats";
export {
  buildWeaponDpsIndex,
  extractTraitPerksFromRow,
  formatBuildDescription,
  formatWeaponDpsLabel,
  formatWeaponDpsParts,
  matchSheetRowToWeapon,
  parseDpsNumber,
  parseTotalDamage,
  weaponDpsLookupFromIndex,
  WEAPON_DPS_SHEET_CSV_URL,
  WEAPON_DPS_SHEET_NAME,
  WEAPON_DPS_SHEET_URL,
  type WeaponDpsCatalogEntry,
  type WeaponDpsEntry,
  type WeaponDpsIndex,
  type WeaponDpsLookup,
} from "./weapon-dps";
